services:
  project_db:
    image: mysql:latest
    container_name: project_db
    restart: always
    environment:
      - MYSQL_USER=toandfro_user
      - MYSQL_ROOT_PASSWORD=toandfro_password
      - MYSQL_PASSWORD=toandfro_password
      - MYSQL_DATABASE=toandfro_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: